 hosts: all
  gather_facts: no
  #remote_user: myuser
  #serial: "25%"
  #sudo: yes
  tasks:

    - name: rpm2cvescan-ansible - removing file /tmp/rpm2cvescan-ansible.log
      file: path=/tmp/rpm2cvescan-ansible.log state=absent
      delegate_to: 127.0.0.1

    - name: rpm2cvescan-ansible - creating file /tmp/rpm2cvescan-ansible.log
      file: path=/tmp/rpm2cvescan-ansible.log state=touch
      delegate_to: 127.0.0.1

    - name: rpm2cvescan-ansible - grabbing rpm output from remote hosts
      environment:
        LC_MESSAGES: 'C'
      shell: echo $(hostname -f):::$(/bin/rpm --nosignature --nodigest -qf /etc/redhat-release --qf '%{N}-%{V}-%{R}'):::$(/bin/rpm --nosignature --nodigest -qa --qf '%{N}-%{epochnum}:%{V}-%{R} %{N}\n'|tr '\n' ','|sed 's/,$//'):::$(/bin/rpm --nosignature --nodigest -qa --qf '%{N}-%{epochnum}:%{V}-%{R} %{N}-%{V}-%{R}\n'|tr '\n' ','|sed 's/,$//' )|sed 's/\(.*\)\r/\"\1\"/g; s/\(.*\)/\"\1\"/g'
      register: rpm_register_version

    - name: rpm2cvescan-ansible - set fact rpm_output
      set_fact:
          rpm_output: "{{ rpm_register_version.stdout|from_json }}"

    - name: rpm2cvescan-ansible - writing to /tmp/rpm2cvescan-ansible.log
      lineinfile:
         line: "{{ rpm_output }}"
         insertafter: EOF
         dest: /tmp/rpm2cvescan-ansible.log
      delegate_to: 127.0.0.1

